volumes:
  prd_postgres_data:
    driver: local

services:
  postgres:
    image: postgres:17
    volumes:
      - prd_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "Postgres2022!"
    restart: always
  app:
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile
      target: prd
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "Postgres2022!"
      DB_HOST: "localhost"
      DB_PORT: 5432
      DB_SEED: 0
      DB_BUILD: 1
    restart: always